// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: iims.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	CreationDate  string                 `protobuf:"bytes,3,opt,name=CreationDate,proto3" json:"CreationDate,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertProductRequest) Reset() {
	*x = InsertProductRequest{}
	mi := &file_iims_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertProductRequest) ProtoMessage() {}

func (x *InsertProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertProductRequest.ProtoReflect.Descriptor instead.
func (*InsertProductRequest) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{0}
}

func (x *InsertProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InsertProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InsertProductRequest) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *InsertProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetByIdProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdProductRequest) Reset() {
	*x = GetByIdProductRequest{}
	mi := &file_iims_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdProductRequest) ProtoMessage() {}

func (x *GetByIdProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdProductRequest.ProtoReflect.Descriptor instead.
func (*GetByIdProductRequest) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIdProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InsertProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertProductResponse) Reset() {
	*x = InsertProductResponse{}
	mi := &file_iims_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertProductResponse) ProtoMessage() {}

func (x *InsertProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertProductResponse.ProtoReflect.Descriptor instead.
func (*InsertProductResponse) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{2}
}

func (x *InsertProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_iims_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetProductsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetProductMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CreationDate  string                 `protobuf:"bytes,4,opt,name=CreationDate,proto3" json:"CreationDate,omitempty"`
	Price         string                 `protobuf:"bytes,5,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductMessage) Reset() {
	*x = GetProductMessage{}
	mi := &file_iims_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductMessage) ProtoMessage() {}

func (x *GetProductMessage) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductMessage.ProtoReflect.Descriptor instead.
func (*GetProductMessage) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetProductMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetProductMessage) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *GetProductMessage) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type GetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*GetProductMessage   `protobuf:"bytes,1,rep,name=Products,proto3" json:"Products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_iims_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductsResponse) GetProducts() []*GetProductMessage {
	if x != nil {
		return x.Products
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_iims_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CreationDate  string                 `protobuf:"bytes,4,opt,name=CreationDate,proto3" json:"CreationDate,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_iims_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BlockProductOperationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockProductOperationMessage) Reset() {
	*x = BlockProductOperationMessage{}
	mi := &file_iims_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockProductOperationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockProductOperationMessage) ProtoMessage() {}

func (x *BlockProductOperationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockProductOperationMessage.ProtoReflect.Descriptor instead.
func (*BlockProductOperationMessage) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{8}
}

func (x *BlockProductOperationMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InsertSaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	SaleSize      int32                  `protobuf:"varint,3,opt,name=SaleSize,proto3" json:"SaleSize,omitempty"`
	Product       string                 `protobuf:"bytes,4,opt,name=Product,proto3" json:"Product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertSaleRequest) Reset() {
	*x = InsertSaleRequest{}
	mi := &file_iims_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertSaleRequest) ProtoMessage() {}

func (x *InsertSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertSaleRequest.ProtoReflect.Descriptor instead.
func (*InsertSaleRequest) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{9}
}

func (x *InsertSaleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InsertSaleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InsertSaleRequest) GetSaleSize() int32 {
	if x != nil {
		return x.SaleSize
	}
	return 0
}

func (x *InsertSaleRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

type InsertSaleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertSaleResponse) Reset() {
	*x = InsertSaleResponse{}
	mi := &file_iims_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertSaleResponse) ProtoMessage() {}

func (x *InsertSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertSaleResponse.ProtoReflect.Descriptor instead.
func (*InsertSaleResponse) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{10}
}

func (x *InsertSaleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSalesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesRequest) Reset() {
	*x = GetSalesRequest{}
	mi := &file_iims_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesRequest) ProtoMessage() {}

func (x *GetSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesRequest.ProtoReflect.Descriptor instead.
func (*GetSalesRequest) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{11}
}

func (x *GetSalesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetSalesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetSaleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	SaleSize      int32                  `protobuf:"varint,4,opt,name=SaleSize,proto3" json:"SaleSize,omitempty"`
	Product       string                 `protobuf:"bytes,5,opt,name=Product,proto3" json:"Product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSaleMessage) Reset() {
	*x = GetSaleMessage{}
	mi := &file_iims_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSaleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleMessage) ProtoMessage() {}

func (x *GetSaleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleMessage.ProtoReflect.Descriptor instead.
func (*GetSaleMessage) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{12}
}

func (x *GetSaleMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSaleMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSaleMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetSaleMessage) GetSaleSize() int32 {
	if x != nil {
		return x.SaleSize
	}
	return 0
}

func (x *GetSaleMessage) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

type GetSalesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sales         []*GetSaleMessage      `protobuf:"bytes,1,rep,name=Sales,proto3" json:"Sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalesResponse) Reset() {
	*x = GetSalesResponse{}
	mi := &file_iims_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalesResponse) ProtoMessage() {}

func (x *GetSalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalesResponse.ProtoReflect.Descriptor instead.
func (*GetSalesResponse) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{13}
}

func (x *GetSalesResponse) GetSales() []*GetSaleMessage {
	if x != nil {
		return x.Sales
	}
	return nil
}

type DeleteSaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSaleRequest) Reset() {
	*x = DeleteSaleRequest{}
	mi := &file_iims_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSaleRequest) ProtoMessage() {}

func (x *DeleteSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSaleRequest.ProtoReflect.Descriptor instead.
func (*DeleteSaleRequest) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteSaleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateSaleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	SaleSize      int32                  `protobuf:"varint,4,opt,name=SaleSize,proto3" json:"SaleSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSaleRequest) Reset() {
	*x = UpdateSaleRequest{}
	mi := &file_iims_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSaleRequest) ProtoMessage() {}

func (x *UpdateSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSaleRequest.ProtoReflect.Descriptor instead.
func (*UpdateSaleRequest) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateSaleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSaleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSaleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSaleRequest) GetSaleSize() int32 {
	if x != nil {
		return x.SaleSize
	}
	return 0
}

type BlockSaleOperationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSaleOperationMessage) Reset() {
	*x = BlockSaleOperationMessage{}
	mi := &file_iims_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSaleOperationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSaleOperationMessage) ProtoMessage() {}

func (x *BlockSaleOperationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_iims_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSaleOperationMessage.ProtoReflect.Descriptor instead.
func (*BlockSaleOperationMessage) Descriptor() ([]byte, []int) {
	return file_iims_proto_rawDescGZIP(), []int{16}
}

func (x *BlockSaleOperationMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_iims_proto protoreflect.FileDescriptor

const file_iims_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"iims.proto\x12\x03uas\x1a\x1bgoogle/protobuf/empty.proto\"\x86\x01\n" +
	"\x14InsertProductRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\"\n" +
	"\fCreationDate\x18\x03 \x01(\tR\fCreationDate\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\x02R\x05Price\"'\n" +
	"\x15GetByIdProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15InsertProductResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\"B\n" +
	"\x12GetProductsRequest\x12\x14\n" +
	"\x05Limit\x18\x01 \x01(\x03R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x02 \x01(\x03R\x06Offset\"\x93\x01\n" +
	"\x11GetProductMessage\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\"\n" +
	"\fCreationDate\x18\x04 \x01(\tR\fCreationDate\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\tR\x05Price\"I\n" +
	"\x13GetProductsResponse\x122\n" +
	"\bProducts\x18\x01 \x03(\v2\x16.uas.GetProductMessageR\bProducts\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\"\x96\x01\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\"\n" +
	"\fCreationDate\x18\x04 \x01(\tR\fCreationDate\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x02R\x05Price\".\n" +
	"\x1cBlockProductOperationMessage\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\"\x7f\n" +
	"\x11InsertSaleRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x1a\n" +
	"\bSaleSize\x18\x03 \x01(\x05R\bSaleSize\x12\x18\n" +
	"\aProduct\x18\x04 \x01(\tR\aProduct\"$\n" +
	"\x12InsertSaleResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\"?\n" +
	"\x0fGetSalesRequest\x12\x14\n" +
	"\x05Limit\x18\x01 \x01(\x03R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x02 \x01(\x03R\x06Offset\"\x8c\x01\n" +
	"\x0eGetSaleMessage\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1a\n" +
	"\bSaleSize\x18\x04 \x01(\x05R\bSaleSize\x12\x18\n" +
	"\aProduct\x18\x05 \x01(\tR\aProduct\"=\n" +
	"\x10GetSalesResponse\x12)\n" +
	"\x05Sales\x18\x01 \x03(\v2\x13.uas.GetSaleMessageR\x05Sales\"#\n" +
	"\x11DeleteSaleRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\"u\n" +
	"\x11UpdateSaleRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1a\n" +
	"\bSaleSize\x18\x04 \x01(\x05R\bSaleSize\"+\n" +
	"\x19BlockSaleOperationMessage\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id2\xed\x03\n" +
	"\x0eProductService\x12D\n" +
	"\tInsertOne\x12\x19.uas.InsertProductRequest\x1a\x1a.uas.InsertProductResponse\"\x00\x12:\n" +
	"\x03Get\x12\x17.uas.GetProductsRequest\x1a\x18.uas.GetProductsResponse\"\x00\x12?\n" +
	"\aGetById\x12\x1a.uas.GetByIdProductRequest\x1a\x16.uas.GetProductMessage\"\x00\x12=\n" +
	"\x06Delete\x12\x19.uas.DeleteProductRequest\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\x06Update\x12\x19.uas.UpdateProductRequest\x1a\x16.google.protobuf.Empty\"\x00\x12K\n" +
	"\fBlockProduct\x12!.uas.BlockProductOperationMessage\x1a\x16.google.protobuf.Empty\"\x00\x12M\n" +
	"\x0eUnblockProduct\x12!.uas.BlockProductOperationMessage\x1a\x16.google.protobuf.Empty\"\x002\x8b\x03\n" +
	"\vSaleService\x12>\n" +
	"\tInsertOne\x12\x16.uas.InsertSaleRequest\x1a\x17.uas.InsertSaleResponse\"\x00\x124\n" +
	"\x03Get\x12\x14.uas.GetSalesRequest\x1a\x15.uas.GetSalesResponse\"\x00\x12:\n" +
	"\x06Delete\x12\x16.uas.DeleteSaleRequest\x1a\x16.google.protobuf.Empty\"\x00\x12:\n" +
	"\x06Update\x12\x16.uas.UpdateSaleRequest\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\tBlockSale\x12\x1e.uas.BlockSaleOperationMessage\x1a\x16.google.protobuf.Empty\"\x00\x12G\n" +
	"\vUnblockSale\x12\x1e.uas.BlockSaleOperationMessage\x1a\x16.google.protobuf.Empty\"\x00B(Z&github.com/igntnk/stocky_iims/proto/pbb\x06proto3"

var (
	file_iims_proto_rawDescOnce sync.Once
	file_iims_proto_rawDescData []byte
)

func file_iims_proto_rawDescGZIP() []byte {
	file_iims_proto_rawDescOnce.Do(func() {
		file_iims_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iims_proto_rawDesc), len(file_iims_proto_rawDesc)))
	})
	return file_iims_proto_rawDescData
}

var file_iims_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_iims_proto_goTypes = []any{
	(*InsertProductRequest)(nil),         // 0: uas.InsertProductRequest
	(*GetByIdProductRequest)(nil),        // 1: uas.GetByIdProductRequest
	(*InsertProductResponse)(nil),        // 2: uas.InsertProductResponse
	(*GetProductsRequest)(nil),           // 3: uas.GetProductsRequest
	(*GetProductMessage)(nil),            // 4: uas.GetProductMessage
	(*GetProductsResponse)(nil),          // 5: uas.GetProductsResponse
	(*DeleteProductRequest)(nil),         // 6: uas.DeleteProductRequest
	(*UpdateProductRequest)(nil),         // 7: uas.UpdateProductRequest
	(*BlockProductOperationMessage)(nil), // 8: uas.BlockProductOperationMessage
	(*InsertSaleRequest)(nil),            // 9: uas.InsertSaleRequest
	(*InsertSaleResponse)(nil),           // 10: uas.InsertSaleResponse
	(*GetSalesRequest)(nil),              // 11: uas.GetSalesRequest
	(*GetSaleMessage)(nil),               // 12: uas.GetSaleMessage
	(*GetSalesResponse)(nil),             // 13: uas.GetSalesResponse
	(*DeleteSaleRequest)(nil),            // 14: uas.DeleteSaleRequest
	(*UpdateSaleRequest)(nil),            // 15: uas.UpdateSaleRequest
	(*BlockSaleOperationMessage)(nil),    // 16: uas.BlockSaleOperationMessage
	(*emptypb.Empty)(nil),                // 17: google.protobuf.Empty
}
var file_iims_proto_depIdxs = []int32{
	4,  // 0: uas.GetProductsResponse.Products:type_name -> uas.GetProductMessage
	12, // 1: uas.GetSalesResponse.Sales:type_name -> uas.GetSaleMessage
	0,  // 2: uas.ProductService.InsertOne:input_type -> uas.InsertProductRequest
	3,  // 3: uas.ProductService.Get:input_type -> uas.GetProductsRequest
	1,  // 4: uas.ProductService.GetById:input_type -> uas.GetByIdProductRequest
	6,  // 5: uas.ProductService.Delete:input_type -> uas.DeleteProductRequest
	7,  // 6: uas.ProductService.Update:input_type -> uas.UpdateProductRequest
	8,  // 7: uas.ProductService.BlockProduct:input_type -> uas.BlockProductOperationMessage
	8,  // 8: uas.ProductService.UnblockProduct:input_type -> uas.BlockProductOperationMessage
	9,  // 9: uas.SaleService.InsertOne:input_type -> uas.InsertSaleRequest
	11, // 10: uas.SaleService.Get:input_type -> uas.GetSalesRequest
	14, // 11: uas.SaleService.Delete:input_type -> uas.DeleteSaleRequest
	15, // 12: uas.SaleService.Update:input_type -> uas.UpdateSaleRequest
	16, // 13: uas.SaleService.BlockSale:input_type -> uas.BlockSaleOperationMessage
	16, // 14: uas.SaleService.UnblockSale:input_type -> uas.BlockSaleOperationMessage
	2,  // 15: uas.ProductService.InsertOne:output_type -> uas.InsertProductResponse
	5,  // 16: uas.ProductService.Get:output_type -> uas.GetProductsResponse
	4,  // 17: uas.ProductService.GetById:output_type -> uas.GetProductMessage
	17, // 18: uas.ProductService.Delete:output_type -> google.protobuf.Empty
	17, // 19: uas.ProductService.Update:output_type -> google.protobuf.Empty
	17, // 20: uas.ProductService.BlockProduct:output_type -> google.protobuf.Empty
	17, // 21: uas.ProductService.UnblockProduct:output_type -> google.protobuf.Empty
	10, // 22: uas.SaleService.InsertOne:output_type -> uas.InsertSaleResponse
	13, // 23: uas.SaleService.Get:output_type -> uas.GetSalesResponse
	17, // 24: uas.SaleService.Delete:output_type -> google.protobuf.Empty
	17, // 25: uas.SaleService.Update:output_type -> google.protobuf.Empty
	17, // 26: uas.SaleService.BlockSale:output_type -> google.protobuf.Empty
	17, // 27: uas.SaleService.UnblockSale:output_type -> google.protobuf.Empty
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_iims_proto_init() }
func file_iims_proto_init() {
	if File_iims_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iims_proto_rawDesc), len(file_iims_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_iims_proto_goTypes,
		DependencyIndexes: file_iims_proto_depIdxs,
		MessageInfos:      file_iims_proto_msgTypes,
	}.Build()
	File_iims_proto = out.File
	file_iims_proto_goTypes = nil
	file_iims_proto_depIdxs = nil
}
